apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: hello-agent
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    app: hello-agent
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: hello-agent
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    app: hello-agent
spec:
  output:
    to:
      kind: ImageStreamTag
      name: hello-agent:latest
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  triggers: []

