apiVersion: v1
kind: Service
metadata:
  name: kagent-mlflow-response-adapter
  namespace: mschimun
  labels:
    app: kagent-mlflow-response-agent
spec:
  selector:
    app: kagent-mlflow-response-adapter
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP

