apiVersion: v1
kind: Secret
metadata:
  name: kagent-mlflow-agent-dummy-key
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    app.kubernetes.io/name: kagent-mlflow-agent
type: Opaque
stringData:
  api-key: "fake"


