apiVersion: v1
kind: Service
metadata:
  name: kagent-mlflow-adapter
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    app: kagent-mlflow-adapter
spec:
  selector:
    app: kagent-mlflow-adapter
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP


