apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: vectorstore-setup
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    app: vectorstore-setup
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: vectorstore-setup
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    app: vectorstore-setup
spec:
  output:
    to:
      kind: ImageStreamTag
      name: vectorstore-setup:latest
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  triggers: []

